version: '3.8'

services:
  backend:
    build:
      context: ./mybackend
    ports:
      - "8000:8000"
    volumes:
      - ./mybackend:/app

  frontend:
    build:
      context: ./dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./dashboard:/app
    depends_on:
      - backend

volumes:
  db_data: